insert into categories (id, family_id, name, type, is_custom, is_favorite)
values
  ('salary', null, 'Salario', 'entrada', false, false),
  ('pro_labore', null, 'Pro-labore', 'entrada', false, false),
  ('freelance', null, 'Freelancer/Autonomo', 'entrada', false, false),
  ('commission_bonus', null, 'Comissao/Bonificacao', 'entrada', false, false),
  ('benefits', null, 'Beneficios', 'entrada', false, false),
  ('rent_income', null, 'Aluguel recebido', 'entrada', false, false),
  ('investment_income', null, 'Rendimentos de investimentos', 'entrada', false, false),
  ('reimbursement', null, 'Reembolso', 'entrada', false, false),
  ('casual_sale', null, 'Venda eventual', 'entrada', false, false),
  ('gift_donation_received', null, 'Presente/Doacao recebida', 'entrada', false, false),
  ('other_income', null, 'Outras entradas', 'entrada', false, false),
  ('housing', null, 'Moradia', 'saida', false, false),
  ('utilities', null, 'Contas essenciais', 'saida', false, false),
  ('groceries', null, 'Alimentacao em casa', 'saida', false, false),
  ('dining_out', null, 'Alimentacao fora', 'saida', false, false),
  ('transport', null, 'Transporte', 'saida', false, false),
  ('health', null, 'Saude', 'saida', false, false),
  ('education', null, 'Educacao', 'saida', false, false),
  ('debts_loans', null, 'Dividas e emprestimos', 'saida', false, false),
  ('credit_card', null, 'Cartao de credito', 'saida', false, false),
  ('taxes_fees', null, 'Impostos e taxas', 'saida', false, false),
  ('insurance', null, 'Seguros', 'saida', false, false),
  ('leisure', null, 'Lazer', 'saida', false, false),
  ('subscriptions', null, 'Assinaturas e servicos digitais', 'saida', false, false),
  ('personal_care', null, 'Cuidados pessoais', 'saida', false, false),
  ('clothing', null, 'Vestuario', 'saida', false, false),
  ('children_family', null, 'Filhos/Familia', 'saida', false, false),
  ('pets', null, 'Pets', 'saida', false, false),
  ('home_maintenance', null, 'Manutencao do lar', 'saida', false, false),
  ('travel', null, 'Viagens', 'saida', false, false),
  ('donations', null, 'Doacoes', 'saida', false, false),
  ('investments_contribution', null, 'Investimentos/Aportes', 'saida', false, false),
  ('other_expense', null, 'Outras saidas', 'saida', false, false)
on conflict (id) do nothing;
